import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { httpClientProofProvider } from "@midnight-ntwrk/midnight-js-http-client-proof-provider";
import { indexerPublicDataProvider } from "@midnight-ntwrk/midnight-js-indexer-public-data-provider";
import { NodeZkConfigProvider } from "@midnight-ntwrk/midnight-js-node-zk-config-provider";
import type { ProofProvider, PublicDataProvider, ZKConfigProvider } from "@midnight-ntwrk/midnight-js-types";
import type { MidnightConfig } from "./midnight-config.js";

/** The 4 circuits `avtar-escrow.compact` compiles to separate provable transactions. */
export type AvtarEscrowCircuitId = "whitelistToken" | "openChannel" | "settle" | "refund";

const HERE = dirname(fileURLToPath(import.meta.url));

/** `midnight/contracts/avtar-escrow/managed` — holds `keys/` (prover/verifier) and `zkir/`. */
export const DEFAULT_MANAGED_CONTRACT_DIR = resolve(
  HERE,
  "../midnight/contracts/avtar-escrow/managed",
);

/**
 * The 3 providers that only need network endpoints (no wallet): proving,
 * reading public chain state, and loading the local prover/verifier keys
 * generated by `pnpm compact:build`. These are chain/version-agnostic and
 * safe to build regardless of which `@midnight-ntwrk/midnight-js-contracts`
 * major version ends up wiring the actual deploy/call transactions.
 *
 * NOT included here: `walletProvider` / `midnightProvider` (need a synced
 * wallet from a funded seed) and `privateStateProvider` (needs a password
 * provider + account id) — `avtar-escrow` has no private state
 * (`Witnesses<PS> = {}`), so those matter only for the deploy/call step
 * itself. See `midnight/deploy.mjs`.
 */
export interface MidnightNetworkProviders {
  proofProvider: ProofProvider;
  publicDataProvider: PublicDataProvider;
  zkConfigProvider: ZKConfigProvider<AvtarEscrowCircuitId>;
}

export function buildMidnightNetworkProviders(
  config: MidnightConfig,
  managedContractDir: string = DEFAULT_MANAGED_CONTRACT_DIR,
): MidnightNetworkProviders {
  const zkConfigProvider = new NodeZkConfigProvider<AvtarEscrowCircuitId>(managedContractDir);
  return {
    zkConfigProvider,
    proofProvider: httpClientProofProvider(config.proofServerUrl, zkConfigProvider),
    publicDataProvider: indexerPublicDataProvider(config.indexerUrl, config.indexerWsUrl),
  };
}
